### ISSUE TITLE
change defined_tags_json argument for HCL2 template to use map variable type instead of json string

### ISSUE THREAD

**Issue by luckeyca** [hashicorp/packer-plugin-oracle#121]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

current for HCL2 templates, the variable type is string which is impossible to work with when defining it as variable with values either in variable file as default and/or in a value file. This argument should use the same variable type as the old json format AND to be consistent with the variable types in terraform which are all map object.

See the issue as report here: https://github.com/hashicorp/packer-plugin-oracle/issues/120

#### Use Case(s)

see description above.

#### Potential configuration

```
variable "defined_tags" {
type = map(object) or map(any)
}
```

**Comment by lbajolet-hashicorp** [comment]
As explained in #120, this is due to HCL2/cty limitations and the fact that data has to be defined with a schema in order to allow deserialisation to Go structures, so this will stay as-is for now.

**Comment by luckeyca** [comment]
The reason for this ticket was due to the misleading documentation online here: https://developer.hashicorp.com/packer/integrations/hashicorp/oracle/latest/components/builder/oci. It says map(map(string)) is for json syntax ONLY, for hcl2 syntax, it only points to "string". From the test results, this is not the case because defined_tag_json can also be map of map of strings type. This was what caused the confusion and what I was looking for as map is much easier to use that json text string.

This is the section needs to be updated to say defined_tags_json can also be map of map of strings for HCL2 syntax.
```
defined_tags_json (string) - JSON string to add one or more defined tags for a given namespace to the resulting custom image. Only works on HCL2 templates. For old-style JSON templates, use [defined_tags]

defined_tags (map of map of strings) - Add one or more defined tags for a given namespace to the resulting custom image. Only works on old-style JSON templates. For HCL2 templates, use [defined_tags_json](https://developer.hashicorp.com/packer/integrations/hashicorp/oracle/latest/components/builder/oci#defined_tags_json) instead. See [the Oracle docs](https://docs.cloud.oracle.com/iaas/Content/Identity/Concepts/taggingoverview.htm) for more details.
```
