### ISSUE TITLE
Support for ImageCapabilities (e.g. Network.AttachmentType)

### ISSUE THREAD

**Issue by robert-heinzmann-logmein** [hashicorp/packer-plugin-oracle#46]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Currently packer does not support specifying additional "Image Capabilities" (see https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/configuringimagecapabilities.htm) for Images. As currently OKE does not support specifying the network type of nodes to start, the default is "PARAVIRTUAL" which might have a very low performance. To use a custom image in OKE that is built by packer, it would be awesome to have the capability to set custom capabilities on images (e.g. `Network.AttachmentType` to VFIO) in the packer build already, so that new nodes coming up will have SR-IOV enabled.

#### Use Case(s)

High performance OKE nodes using custom images.

#### Potential References

https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/configuringimagecapabilities.htm

**Comment by eshneken** [comment]
LaunchMode (paravirtualized, native, etc) and NICAttachmentType (E1000, paravirtualized, VFIO) can only be set by updating the ComputeImageCapabilitySchema (https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/ComputeImageCapabilitySchema/UpdateComputeImageCapabilitySchema) which is a new aspect added to OCI.  Provider needs to be updated to latest version of the golang SDK and to update the schema on image creation.
