### ISSUE TITLE
Add typically required policy to the docs

### ISSUE THREAD

**Issue by b-dean** [hashicorp/packer-plugin-oracle#59]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Add documentation of the IAM policies typically needed to run the OCI packer builder.

#### Use Case(s)

Best practice is to give users the minimal required permissions. This should be documented in the plugin what permissions are needed to run OCI's builder. It can be difficult to find all the minimal required policies from the OCI documentation.

Also, for what it's worth, the AWS builder for packer has [documentation on the required IAM permissions](https://www.packer.io/plugins/builders/amazon#iam-task-or-instance-role). It is a very useful reference for configuring a user or role in AWS to be able to build AMIs.

**Comment by eshneken** [comment]
@nywilken I think this can also be closed given the addition of IAM info into the docs

**Comment by nywilken** [comment]
The required policies have been documented at https://developer.hashicorp.com/packer/integrations/hashicorp/oracle#policy-reference

I'm closing this issue. If you find that you are still running into issues getting started leave a comment and we will help get things straight.
