### ISSUE TITLE
Error updating image schema

### ISSUE THREAD

**Issue by youngturk2** [hashicorp/packer-plugin-oracle#95]
#### Overview of the Issue

Part of me even wonders if I should create this issue, as packer IS creating the custom image successfully, but I feel I should still report this, since, given the above information, it is odd that the plugin is still reporting an error at the end of the process.  So, after packer and the plugin finish building the image, the plugin begins creating the custom image, but then, in the very next step, when it is "updating the version schema", the plugin produces an error.  See the gist file linked below for logs and exact errors.  Again, however, I want to emphasize that the custom image **IS** created at the end of the process, despite the fact that the plugin is reporting otherwise.

![image](https://github.com/hashicorp/packer-plugin-oracle/assets/116093277/63c606b8-ab06-4ea2-bde9-1a8fae0f86a1)

#### Reproduction Steps

1. With a packer build file modeled after the packer config included below, run the following commands
  1. packer init .
  2. packer validate .
  3. packer build .

### Plugin and Packer version

packer version: 1.9.1
Plugin version: 1.0.4

### Simplified Packer Buildfile

https://gist.github.com/youngturk2/89265e51da49dd03006837499934b061

### Operating system and Environment details

Microsoft Windows Server 2016 Standard x64

### Log Fragments and crash.log files

https://gist.github.com/youngturk2/688032398bb1ac548818272f5d6220f6

**Comment by youngturk2** [comment]
Have to say.  The dedication you all have demonstrated through your timely responses to posted issues to provide a quality product is inspiring.  10/10.

**Comment by eshneken** [comment]
What policies does the user who is running this have set? Do you have, at minimum, the following policies set?

Allow group PackerGroup to manage instance-family in compartment ${COMPARTMENT_NAME}
Allow group PackerGroup to manage instance-images in compartment ${COMPARTMENT_NAME}
Allow group PackerGroup to use virtual-network-family in compartment ${COMPARTMENT_NAME}
Allow group PackerGroup to use compute-image-capability-schema in tenancy

@nywilken We added policy documentation but the links to that documentation doesn't seem to link correctly from this page: https://github.com/hashicorp/packer-plugin-oracle/tree/main/docs. Are you able to update?

**Comment by nywilken** [comment]
@eshneken I opened #106 to address the documentation issue. A preview of the README can be found [here](https://github.com/hashicorp/packer-plugin-oracle/blob/30d410ad315f9a2eab6958cf240637b1e5e743d2/docs/README.md). 

@youngturk2 does the information provided by @eshneken help resolve the issue?

**Comment by nywilken** [comment]
@eshneken it looks like https://github.com/hashicorp/packer-plugin-oracle/pull/110 may be related and possibly fixes any inconsistency reported in this issue. Please let me know if this issue is safe to close now that #86 has been merged.

**Comment by eshneken** [comment]
@nywilken I think between documentation of the policies and updates in #110 I think it is reasonable to also close this issue unless the original commenter is still seeing an issue after re-testing with the latest plugin build and proper policies set.  Based on previous responses from the reporter in this thread, I'm guessing he is not planning on re-engaging so my vote is to close.
